# Generated by Django 3.1.6 on 2021-02-12 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 12, 11, 39, 41, 789180, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 2, 12, 11, 39, 41, 788181, tzinfo=utc)),
        ),
    ]
